project:
  type: website

website:
  title: "Keller Group Lab Manual"
  navbar:
      background: light
      title: false
      left:
       - text: "Welcome!"
         href: index.qmd
       - text: "Lab Values"
         href: docs/lab-values/index.qmd
       - text: "Onboarding"
         href: docs/onboarding/index.qmd
       - text: "Guide"
         href: docs/guide/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



