---
title: "Reading List"
format: 
  html: default
---

## General Reading

::: {.wrap-list}
* Oreskes, N., Shrader-Frechette, K. and Belitz, K. (1994). Verification, validation, and confirmation of numerical models in the Earth sciences. Science, 263(5147), pp. 641–646. <https://doi.org/10.1126/science.263.5147.641>.
* Rittel, H. W. J., & Webber, M. M. (1973). Dilemmas in a general theory of planning. Policy Sciences, 4(2), 155–169. <https://doi.org/10.1007/bf01405730>
* Lindblom, C.E. (1959). The Science of “Muddling Through”. Public administration review, 19(2), pp. 79–88. <https://doi.org/10.2307/973677>.
* Ackoff, R. A. (1979). The Future of Operational Research is Past. The Journal of the Operational Research Society 30(2): 93-104.
* Baron, N. (2010). Escape from the ivory tower: a guide to making your science matter (1st ed.). Island Press.
* Keller, K., Helgeson, C., & Srikrishnan, V. (2021). Climate risk management. Annual Review of Earth and Planetary Sciences, 49, 95-116. <https://doi.org/10.1146/annurev-earth-080320-055847>
* Reed, P. M., Hadjimichael, A., Malek, K., Karimi, T., Vernon, C. R., Srikrishnan, V., et al. (2022). Addressing Uncertainty in MultiSector Dynamics Research. <https://immm-sfa.github.io/msd_uncertainty_ebook/>
* Reed, P. M., Hadjimichael, A., Moss, R. H., Brelsford, C., Burleyson, C. D., Cohen, S., et al. (2022). Multisector dynamics: Advancing the science of complex adaptive human-earth systems. Earth’s Future, 10(3). <https://doi.org/10.1029/2021ef002621>
* Pollack, A.B. et al. (2026). Unlocking the benefits of transparent and reusable science for climate risk management. Proceedings of the National Academy of Sciences, 123(3), p. e2422157123. <https://doi.org/10.1073/pnas.2422157123>.
* Rudin, C. (2019). Stop explaining black box machine learning models for high stakes decisions and use interpretable models instead. Nature machine intelligence, 1(5), pp. 206–215. <https://doi.org/10.1038/s42256-019-0048-x>.
* Little, R.J. (2013). In praise of simplicity not mathematistry! Ten simple powerful ideas for the statistical scientist. Journal of the American Statistical Association, 108(502), pp. 359–369. <https://doi.org/10.1080/01621459.2013.787932>.
* Roberts, D.R. et al. (2017). Cross‐validation strategies for data with temporal, spatial, hierarchical, or phylogenetic structure. Ecography, 40(8), pp. 913–929. <https://doi.org/10.1111/ecog.02881>.
* Condon, M. (2023). Climate Services: The Business of Physical Risk. Arizona State law journal, 55(147). <https://doi.org/10.2139/ssrn.4396826>.
* Bistline, J., Budolfson, M. and Francis, B. (2021). Deepening transparency about value-laden assumptions in energy and environmental modelling: improving best practices for both modellers and non-modellers. Climate Policy, 21(1), pp. 1–15. <https://doi.org/10.1080/14693062.2020.1781048>.
* Nolte, C. et al. (2023). Data Practices for Studying the Impacts of Environmental Amenities and Hazards with Nationwide Property Data. Land economics [Preprint]. <https://doi.org/10.3368/le.100.1.102122-0090R>.
* Thompson, E.L. and Smith, L.A. (2019). Escape from model-land. Economics, 13(1). <https://doi.org/10.5018/economics-ejournal.ja.2019-40>.
* Helgeson, C. et al. (2021). Why Simpler Computer Simulation Models Can Be Epistemically Better for Informing Decisions’, Philosophy of science, 88(2), pp. 213–233. <https://doi.org/10.1086/711501>.

:::

## Flood Risk Management
::: {.wrap-list}
* Kunreuther, H. et al. (2013). Risk management and climate change. Nature climate change, 3(5), pp. 447–450. <https://doi.org/10.1038/nclimate1740>.
* Merz, B. et al. (2010). Review article “Assessment of economic flood damage”. Natural Hazards and Earth System Sciences, 10(8), pp. 1697–1724. <https://doi.org/10.5194/nhess-10-1697-2010>.
* Pollack, A.B. et al. (2025). Funding rules that promote equity in climate adaptation outcomes. Proceedings of the National Academy of Sciences, 122(2), p. e2418711121. <https://doi.org/10.1073/pnas.2418711121>.
* Donahue, A.K. and Joyce, P.G. (2001). A framework for analyzing emergency management with an application to federal budgeting. Public administration review, 61(6), pp. 728–740. <https://doi.org/10.1111/0033-3352.00143>.
* Smith, G., Lyles, W. and Berke, P. (2013). The role of the state in building local capacity and commitment for hazard mitigation planning. International journal of mass emergencies and disasters, 31(2), pp. 178–203. <https://doi.org/10.1177/028072701303100204>.
* Rufat, S. et al. (2019). How valid are social vulnerability models?. Annals of the American Association of Geographers, 109(4), pp. 1131–1153. <https://doi.org/10.1080/24694452.2018.1535887>.
* Miao, Q. et al. (2024). Fiscal implications of disasters and the managed retreat thereafter: Evidence from hurricane sandy. Natural hazards review, 25(4), p. 04024036. <https://doi.org/10.1061/nhrefo.nheng-2027>.
* Schubert, J.E., Mach, K.J. and Sanders, B.F. (2024). National‐scale flood hazard data unfit for urban risk management. Earth’s future, 12(7), p. e2024EF004549. <https://doi.org/10.1029/2024ef004549>.
* Molinari, D. et al. (2019). Validation of flood risk models: Current practice and possible improvements. International Journal of Disaster Risk Reduction, 33, pp. 441–448. <https://doi.org/10.1016/j.ijdrr.2018.10.022>.
* Schröter, K. et al. (2014). How useful are complex flood damage models?. Water resources research, 50(4), pp. 3378–3395. <https://doi.org/10.1002/2013wr014396>.
* Kousky, C. (2019). The Role of Natural Disaster Insurance in Recovery and Risk Reduction. Annual Review of Resource Economics, 11(1), pp. 399–418. <https://doi.org/10.1146/annurev-resource-100518-094028>.
* Lowe, K., Reckhow, S. and Gainsborough, J.F. (2016). Capacity and equity: Federal funding competition between and within metropolitan regions. Journal of urban affairs, 38(1), pp. 25–41. <https://doi.org/10.1111/juaf.12203>.
* Gourevitch, J.D. et al. (2023). Unpriced climate risk and the potential consequences of overvaluation in US housing markets. Nature climate change, pp. 1–8. <https://doi.org/10.1038/s41558-023-01594-8>.
* Pollack, A.B. et al. (2023). Potential Benefits in Remapping the Special Flood Hazard Area: Evidence from the U.S. Housing Market. Journal of housing economics, 61, p. 101956. <https://doi.org/10.1016/j.jhe.2023.101956>.
* Hennighausen, H. et al. (2023). Flood insurance reforms, housing market dynamics, and adaptation to climate risks. Journal of housing economics, 62, p. 101953. <https://doi.org/10.1016/j.jhe.2023.101953>.
* Pollack, A.B., Sue Wing, I. and Nolte, C. (2022). Aggregation bias and its drivers in large‐scale flood loss estimation: A Massachusetts case study’, Journal of Flood Risk Management. <https://onlinelibrary.wiley.com/doi/abs/10.1111/jfr3.12851>.
* Vilá, O. et al. (2022). Equity in FEMA hazard mitigation assistance programs: The role of state hazard mitigation officers. Environmental science & policy, 136, pp. 632–641. <https://doi.org/10.1016/j.envsci.2022.07.027>.
* Bradt, J.T., Kousky, C. and Wing, O.E.J. (2021). Voluntary purchases and adverse selection in the market for flood insurance. Journal of environmental economics and management, 110, p. 102515. <https://doi.org/10.1016/j.jeem.2021.102515>.
* Deryugina, T. (2017). The Fiscal Cost of Hurricanes: Disaster Aid versus Social Insurance. American Economic Journal: Economic Policy, 9(3), pp. 168–198. <https://doi.org/10.1257/pol.20140296>.
* Pralle, S. (2019). Drawing lines: FEMA and the politics of mapping flood zones. Climatic change, 152(2), pp. 227–237. <https://doi.org/10.1007/s10584-018-2287-y>.
* Dineva Polina K. et al. (2023). Promoting Spatial Coordination in Flood Buyouts in the United States: Four Strategies and Four Challenges from the Economics of Land Preservation Literature. Natural Hazards Review, 24(1), p. 05022013. <https://doi.org/10.1061/NHREFO.NHENG-1564>.
* BenDor Todd K. et al. (2020) .Floodplain Buyouts and Municipal Finance. Natural Hazards Review, 21(3), p. 04020020. <https://doi.org/10.1061/(ASCE)NH.1527-6996.0000380>.
* Gotham, K.F. (2014). Reinforcing Inequalities: The Impact of the CDBG Program on Post-Katrina Rebuilding. Housing policy debate, 24(1), pp. 192–212. <https://EconPapers.repec.org/RePEc:taf:houspd:v:24:y:2014:i:1:p:192-212 (Accessed: 15 December 2022)>.
* Kind, J., Wouter Botzen, W.J. and Aerts, J.C.J.H. (2017). Accounting for risk aversion, income distribution and social welfare in cost‐benefit analysis for flood risk management. Wiley interdisciplinary reviews. Climate change, 8(2), p. e446. <https://doi.org/10.1002/wcc.446>.
* Siders, A.R. (2019). Social justice implications of US managed retreat buyout programs. Climatic change, 152(2), pp. 239–257. <https://doi.org/10.1007/s10584-018-2272-5>.
* Johnson, C., Penning-Rowsell, E. and Parker, D. (2007). Natural and Imposed Injustices: The Challenges in Implementing “Fair” Flood Risk Management Policy in England. The Geographical journal, 173(4), pp. 374–390. <http://www.jstor.org/stable/30130632>.
* Elliott, J.R., Loughran, K. and Brown, P.L. (2021). Divergent Residential Pathways from Flood-Prone Areas: How Neighborhood Inequalities Are Shaping Urban Climate Adaptation. Social problems. <https://doi.org/10.1093/socpro/spab059>.
* Tate, E. et al. (2016). Flood recovery and property acquisition in Cedar Rapids, Iowa. Natural Hazards, 80(3), pp. 2055–2079. <https://doi.org/10.1007/s11069-015-2060-8>.
* Ciullo, A. et al. (2020). Efficient or Fair? Operationalizing Ethical Principles in Flood Risk Management: A Case Study on the Dutch-German Rhine. Risk Analysis. 40(9), pp. 1844–1862. <https://doi.org/10.1111/risa.13527>.
* Gourevitch, J. D., French, K., Kousky, C., Liao, Y. (Penny), Pollack, A., & Weill, J. A. (2026). Managing Unpriced Climate Risks in US Housing Markets. Review of Environmental Economics and Policy, 0(0), 000–000. <https://doi.org/10.1086/741732>
* Consoer, M., & Milman, A. (2018). Opportunities, constraints, and choices for flood mitigation in rural areas: Perspectives of municipalities in Massachusetts. Journal of Flood Risk Management, 11(2), 141–151. <https://doi.org/10.1111/jfr3.12302>
* Santamaria-Aguilar, S., Maduwantha, P., Enriquez, A. R., & Wahl, T. (2026). Large discrepancies between event- and response-based compound flood hazard estimates. Natural Hazards and Earth System Sciences, 26(1), 571–586. <https://doi.org/10.5194/nhess-26-571-2026>
* Roberts, P. S., Velotti, L., & Wernstedt, K. (2021). How Public Managers Make Tradeoffs Regarding Lives: Evidence From a Flood Planning Survey Experiment. Administration & Society, 53(4), 496–526. <https://doi.org/10.1177/0095399720944811>
* Pollack, A., Doss-Gollin, J., Srikrishnan, V., & Keller, K. (2025). UNSAFE: An UNcertain Structure And Fragility Ensemble framework for property-level flood risk estimation. Journal of Open Source Software, 10(115), 7527. <https://doi.org/10.21105/joss.07527>
* Bhaduri, P., Pollack, A. B., Yoon, J., Roy Chowdhury, P. K., Wan, H., Judi, D., Daniel, B., & Srikrishnan, V. (2025). Uncertainty in household behavior drives large variation in the size of the levee effect. Journal of Flood Risk Management, 18(4), e70131. <https://doi.org/10.1111/jfr3.70131>

:::

## Environmental Justice 
::: {.wrap-list}

* Cole, L. W. and S. R. Foster (2001). From the ground up: Environmental racism and the rise 
of the environmental justice movement. New York, NYU Press.
* Bullard, R. (1994). The Legacy of American Apartheid and Environmental Racism. Journal of Civil Rights and Economic Development, 9(2), pp. 445–474. <https://www.semanticscholar.org/paper/d1fd6ba586dd848aaa5a14f400081015c528a07a (Accessed: 26 October 2022)>.
* Been, V. (1994). Locally undesirable land uses in minority neighborhoods: Disproportionate siting or market dynamics?, The Yale Law Journal, 103(6), p. 1383. <https://doi.org/10.2307/797089>.
* Mohai, P., Pellow, D. and Roberts, J.T. (2009). Environmental Justice. Annual review of environment and resources, 34(1), pp. 405–430. <https://doi.org/10.1146/annurev-environ-082508-094348>.
* Woods, L.L. (2012). The Federal Home Loan Bank Board, Redlining, and the National Proliferation of Racial Lending Discrimination, 1921–1950. Journal of urban history, 38(6), pp. 1036–1059. <https://doi.org/10.1177/0096144211435126>.
* Fishback, P. et al. (2022). New evidence on redlining by federal housing programs in the 1930s, Journal of Urban Economics, 141(103462), p. 103462. <https://doi.org/10.1016/j.jue.2022.103462>.
* Schott, J. and Whyte, K. (2023). Setting Justice40 in Motion: The Hourglass Problem of Infrastructure Justice. Environmental justice , 16(5), pp. 329–339. <https://doi.org/10.1089/env.2022.0046>.
* Seigerman, C.K. et al. (2022). Operationalizing equity for integrated water resources management. Journal of the American Water Resources Association. <https://doi.org/10.1111/1752-1688.13086>.
* Walker, C. and Burningham, K. (2011). Flood Risk, Vulnerability and Environmental Justice: Evidence and Evaluation of Inequality in a UK Context Themed Issue: Social Justice, Social Policy and the Environment. Critical Social Policy, 31(2), pp. 216–240. <https://heinonline.org/HOL/P?h=hein.journals/critsplcy31&i=204>.
* Banzhaf, S., Ma, L. and Timmins, C. (2019). Environmental Justice: the Economics of Race, Place, and Pollution. The journal of economic perspectives: a journal of the American Economic Association, 33(1), pp. 185–208. <https://doi.org/10.1257/jep.33.1.185>.
* Harrison, J. L. (2015). Coopted environmental justice? Activists’ roles in shaping EJ policy implementation. Environmental Sociology, 1(4), 241–255. <https://doi.org/10.1080/23251042.2015.1084682>
* Harrison, J. L. (2017). ‘We do ecology, not sociology’: Interactions among bureaucrats and the undermining of regulatory agencies’ environmental justice efforts. Environmental Sociology, 3(3), 197–212. <https://doi.org/10.1080/23251042.2017.1344918>
* Harrison, J. L. (2023). Environmental justice and the state. Environment and Planning E: Nature and Space, 6(4), 2740–2760. <https://doi.org/10.1177/25148486221138736>
* Pollack, A. B., Helgeson, C., Kousky, C., & Keller, K. (2024). Developing more useful equity measurements for flood-risk management. Nature Sustainability, 7(6), 823–832. <https://doi.org/10.1038/s41893-024-01345-3>


:::

## Social Choice
::: {.wrap-list}
* Simon, H.A. (1956). Rational choice and the structure of the environment. Psychological review, 63(2), pp. 129–138. <https://doi.org/10.1037/h0042769>.
* Savage, L.J. (1951). The theory of statistical decision. Journal of the American Statistical Association, 46(253), pp. 55–67. <https://doi.org/10.1080/01621459.1951.10500768>.
* Sunstein, C.R. (1995). Incompletely Theorized Agreements. Harvard law review, 108(7), pp. 1733–1772. <https://doi.org/10.2307/1341816>.
* Banzhaf, H. (2009). Objective or multi-objective? Two historically competing visions for benefit-cost analysis. Land economics, 85(1), pp. 23–23. <https://doi.org/10.3368/le.85.1.3>.
* Daw, T.M. et al. (2015). Evaluating taboo trade-offs in ecosystems services and human well-being. Proceedings of the National Academy of Sciences of the United States of America, 112(22), pp. 6949–6954. <https://doi.org/10.1073/pnas.1414900112>.
* Vezér, M. et al. (2018). Epistemic and ethical trade-offs in decision analytical modelling. Climatic change, 147(1), pp. 1–10. <https://doi.org/10.1007/s10584-017-2123-9>.
* Jafino, B.A., Kwakkel, J.H. and Taebi, B. (2021). Enabling assessment of distributive justice through models for climate change planning: A review of recent advances and a research agenda. Wiley interdisciplinary reviews. Climate change, 12(4). <https://doi.org/10.1002/wcc.721>.
* Adler, M.D. (2019). Measuring Social Welfare: An Introduction. Oxford University Press. <https://doi.org/10.1093/oso/9780190643027.001.0001>.
* Harsanyi, J.C. (1955). Cardinal Welfare, Individualistic Ethics, and Interpersonal Comparisons of Utility. The journal of political economy, 63(4), pp. 309–321. <http://www.jstor.org/stable/1827128>.
* Anderson, E.S. (1999). What Is the Point of Equality?. Ethics, 109(2), pp. 287–337. <https://doi.org/10.1086/233897>.
* Lamont, J. and Favor, C. (2017). Distributive Justice. The Stanford Encyclopedia of Philosophy. Winter 2017. Edited by E.N. Zalta. Metaphysics Research Lab, Stanford University. <https://plato.stanford.edu/archives/win2017/entries/justice-distributive/>.
* Jafino, B.A., Kwakkel, J.H. and Klijn, F. (2022). Evaluating the distributional fairness of alternative adaptation policies: a case study in Vietnam’s upper Mekong Delta. Climatic change, 173(3), p. 17. <https://doi.org/10.1007/s10584-022-03395-y>.
* Botzen, W.J.W. and van den Bergh, J.C.J.M. (2014). Specifications of Social Welfare in Economic Studies of Climate Policy: Overview of Criteria and Related Policy Insights. Environmental & Resource Economics, 58(1), pp. 1–33. <https://doi.org/10.1007/s10640-013-9738-8>.


:::

## Decision Support
::: {.wrap-list}
* Gregory, R. et al. (2012). Structuring environmental management choices, in Structured Decision Making. Chichester, UK: John Wiley & Sons, Ltd, pp. 1–20. <https://doi.org/10.1002/9781444398557.ch1>.
* Anderies, J.M., Mathias, J.-D. and Janssen, M.A. (2019). Knowledge infrastructure and safe operating spaces in social-ecological systems, Proceedings of the National Academy of Sciences of the United States of America, 116(12), pp. 5277–5284. <https://doi.org/10.1073/pnas.1802885115>.
* Leskens, J.G. et al. (2014). Why are decisions in flood disaster management so poorly supported by information from flood models? Environmental modelling & software, 53, pp. 53–61. <https://doi.org/10.1016/j.envsoft.2013.11.003>.
* Runge, M.C., Converse, S.J. and Lyons, J.E. (2011). Which uncertainty? Using expert elicitation and expected value of information to design an adaptive program. Biological conservation, 144(4), pp. 1214–1223. <https://doi.org/10.1016/j.biocon.2010.12.020>.
* Zulkafli, Z. et al. (2017). User-driven design of decision support systems for polycentric environmental resources management. Environmental modelling & software, 88, pp. 58–73. <https://doi.org/10.1016/j.envsoft.2016.10.012>.
* Helgeson, C. et al. (2024). Integrating values to improve the relevance of climate‐risk research. Earth’s future, 12(10), p. e2022EF003025. <https://doi.org/10.1029/2022ef003025>.
* Lemos, M.C., Kirchhoff, C.J. and Ramprasad, V. (2012). Narrowing the climate information usability gap. Nature climate change, 2(11), pp. 789–794. <https://doi.org/10.1038/nclimate1614>.
* Cash, D.W. et al. (2003). Knowledge systems for sustainable development. Proceedings of the National Academy of Sciences of the United States of America, 100(14), pp. 8086–8091. <https://doi.org/10.1073/pnas.1231332100>.
* Steele, K., Regan, H. M., Colyvan, M., & Burgman, M. A. (2007). Right Decisions or Happy Decision‐makers? Social Epistemology, 21(4), 349–368. <https://doi.org/10.1080/02691720601159711>
* Deslatte, A., Helmke-Long, L., Stokan, E., & Chung, J. (2025). Economies of Inequality? Polycentric Metropolitan Governance and Strategic Sustainability Choices. Urban Affairs Review, 61(2), 315–347. <https://doi.org/10.1177/10780874241252755>
* Krajewski, W. F., Ceynar, D., Demir, I., Goska, R., Kruger, A., Langel, C., Mantilla, R., Niemeier, J., Quintero, F., Seo, B.-C., Small, S. J., Weber, L. J., & Young, N. C. (2017). Real-Time Flood Forecasting and Information System for the State of Iowa. Bulletin of the American Meteorological Society, 98(3), 539–554. <https://doi.org/10.1175/BAMS-D-15-00243.1>
* Hall, J. L. (2008). Assessing Local Capacity for Federal Grant-Getting. The American Review of Public Administration, 38(4), 463–479. <https://doi.org/10.1177/0275074007311385>
* Carlisle, K., & Gruby, R. L. (2019). Polycentric Systems of Governance: A Theoretical Model for the Commons. Policy Studies Journal, 47(4), 927–952. <https://doi.org/10.1111/psj.12212>
* Zellner, M. L., & Massey, D. (2024). Modeling benefits and tradeoffs of green infrastructure: Evaluating and extending parsimonious models for neighborhood stormwater planning. Heliyon, 10(5), e27007. <https://doi.org/10.1016/j.heliyon.2024.e27007>


:::

## Uncertainty and Risk Communication

::: {.wrap-list}
* Morgan, M. G., & Henrion, M. (1995). Uncertainty, a guide to dealing with uncertainty in quantitative policy analysis. Cambridge University Press.
* van der Bles, A. M., van der Linden, S., Freeman, A. L. J., & Spiegelhalter, D. J. (2020). The effects of communicating uncertainty on public trust in facts and numbers. Proceedings of the National Academy of Sciences of the United States of America, 117(14), 7672–7683. <https://doi.org/10.1073/pnas.1913678117>
* Budescu, D. V., Broomell, S., & Por, H.-H. (2009). Improving Communication of Uncertainty in the Reports of the Intergovernmental Panel on Climate Change. Psychological Science, 20(3), 299–308. <https://doi.org/10.1111/j.1467-9280.2009.02284.x>
* Budescu, D. V., Por, H.-H., & Broomell, S. B. (2012). Effective communication of uncertainty in the IPCC reports. Climatic Change, 113(2), 181–200. <https://doi.org/10.1007/s10584-011-0330-3>
* Budescu, D. V., Broomell, S. B., Lempert, R. J., & Keller, K. (2014). Aided and unaided decisions with imprecise probabilities in the domain of losses. EURO Journal on Decision Processes, 2(1), 31–62. <https://doi.org/10.1007/s40070-013-0023-4>
* Budescu, D. V., Por, H.-H., Broomell, S. B., & Smithson, M. (2014). The interpretation of IPCC probabilistic statements around the world. Nature Climate Change, 4(6), 508–512. <https://doi.org/10.1038/nclimate2194>
* Cooper, C.M. et al. (2022) Toward more actionable flood‐risk information. Earth’s future, 10(11). <https://doi.org/10.1029/2022ef003093>
* Ellsberg, D. (1961). Risk, Ambiguity, and the Savage Axioms. The Quarterly Journal of Economics, 75(4), 643–669. <https://doi.org/10.2307/1884324>
* Hobbins, R., Muñoz-Erickson, T. A., & Miller, C. (2021). Producing and Communicating Flood Risk: A Knowledge System Analysis of FEMA Flood Maps in New York City. In Z. A. Hamstead, D. M. Iwaniec, T. McPhearson, M. Berbés-Blázquez, E. M. Cook, & T. A. Muñoz-Erickson (Eds.), Resilient Urban Futures (pp. 67–84). Cham: Springer International Publishing. <https://doi.org/10.1007/978-3-030-63131-4_5>
* Koslov, L. (2019). How maps make time. City, 23(4-5), 658–672. <https://doi.org/10.1080/13604813.2019.1690337>
* Mastrandrea, M. D., Field, C. B., Stocker, T. F., Edenhofer, O., Ebi, K. L., Frame, D. J., et al. (2010). Guidance note for lead authors of the IPCC fifth assessment report on consistent treatment of uncertainties. Retrieved from <http://pubman.mpdl.mpg.de/pubman/item/escidoc:2147184/component/escidoc:2147185/uncertainty-guidance-note.pdf>
* Mastrandrea, M. D., Mach, K. J., Plattner, G.-K., Edenhofer, O., Stocker, T. F., Field, C. B., et al. (2011). The IPCC AR5 guidance note on consistent treatment of uncertainties: a common approach across the working groups. Climatic Change, 108(4), 675. <https://doi.org/10.1007/s10584-011-0178-6>
* Simpson, M., Padilla, L., Keller, K., & Klippel, A. (2022). Immersive storm surge flooding: Scale and risk perception in virtual reality. Journal of Environmental Psychology, (101764), 101764. <https://doi.org/10.1016/j.jenvp.2022.101764>
* Zwick, R., Budescu, D. V., & Wallsten, T. S. (1988). An Empirical Study of the Integration of Linguistic Probabilities. In T. Zétényi (Ed.), Advances in Psychology (Vol. 56, pp. 91–125). North-Holland. <https://doi.org/10.1016/S0166-4115(08)60483-5>
* Ahmad, N., Peterson, N., & Torella, F. (2015). The Micromort: a unit for comparing and communicating risk to patients. International Journal of Clinical Practice, 69(5), 515–517. <https://doi.org/10.1111/ijcp.12643>
* Faulkner, H., Parker, D., Green, C., & Beven, K. (2007). Developing a translational discourse to communicate uncertainty in flood risk between science and the practitioner. Ambio, 36(8), 692–703. Retrieved from <https://www.ncbi.nlm.nih.gov/pubmed/18240686>
* Fischhoff, B. (2014). Four answers to four questions (about risk communication). Journal of Risk Research, 17(10), 1265–1267. <https://doi.org/10.1080/13669877.2014.940598>
* Larrick, R. P., & Soll, J. B. (2008). Economics. The MPG illusion. Science, 320(5883), 1593–1594. <https://doi.org/10.1126/science.1154983>
* Lee, K. D., Torell, G. L., & Newman, S. (2021). A once-in-one-hundred-year event? A survey assessing deviation between perceived and actual understanding of flood risk terminology. Journal of Environmental Management, 277, 111400. <https://doi.org/10.1016/j.jenvman.2020.111400>
* Otway, H., & Wynne, B. (1989). Risk Communication: Paradigm and Paradox. Risk Analysis: An Official Publication of the Society for Risk Analysis, 9(2), 141–145. <https://doi.org/10.1111/j.1539-6924.1989.tb01232.x>
* Spiegelhalter, D. (2017). Risk and Uncertainty Communication. Annual Review of Statistics and Its Application. <https://doi.org/10.1146/annurev-statistics-010814-020148>
:::

## (MO)RDM Reading List
You may want to prioritize the articles in [red]{style="color: red;"}.

### Core/Concepts

::: {.wrap-list}
* [Lempert, R. J. (2019). Robust Decision Making (RDM). In V. A. W. J. Marchau, W. E. Walker, P. J. T. M. Bloemen, & S. W. Popper (Eds.), Decision Making under Deep Uncertainty: From Theory to Practice (pp. 23–51). Cham: Springer International Publishing. <https://doi.org/10.1007/978-3-030-05252-2_2>]{.red}
* [Bankes, Steve. “Exploratory Modeling for Policy Analysis.” Operations Research 41, no. 3 (June 1, 1993): 435–49. <https://doi.org/10.1287/opre.41.3.435>]{.red} 
* [Ellsberg, Daniel. “Risk, Ambiguity, and the Savage Axioms.” The Quarterly Journal of Economics 75, no. 4 (November 1961): 643. https://doi.org/10.2307/1884324]{.red}
* Anderies, J. M., Rodriguez, A. A., Janssen, M. A., & Cifdaloz, O. (2007). Panaceas, uncertainty, and the robust control framework in sustainability science. Proceedings of the National Academy of Sciences of the United States of America, 104(39), 15194–15199. <https://doi.org/10.1073/pnas.0702655104>
* [Herman, J. D., Reed, P. M., Zeff, H. B., & Characklis, G. W. (2015). How should robustness be defined for water systems planning under change?. Journal of Water Resources Planning and Management, 141(10), 04015012.]{.red} 
* Kasprzyk, J. R., Nataraj, S., Reed, P. M., & Lempert, R. J. (2013). Many objective robust decision making for complex environmental systems undergoing change. Environmental Modelling & Software, 42, 55-71. 
* Herman, J.D. et al. (2020). Climate adaptation as a control problem: Review and perspectives on dynamic water resources planning under uncertainty. Water resources research, 56(2). <https://doi.org/10.1029/2019wr025502>.
* McPhail, C., Maier, H. R., Kwakkel, J. H., Giuliani, M., Castelletti, A., & Westra, S. (2018). Robustness metrics: How are they calculated, when should they be used and why do they give different results?. Earth's Future, 6(2), 169-191. 
* [Kwakkel Jan H., Walker Warren E., & Haasnoot Marjolijn. (2016). Coping with the Wickedness of Public Policy Problems: Approaches for Decision Making under Deep Uncertainty. Journal of Water Resources Planning and Management, 142(3), 01816001. <https://doi.org/10.1061/(ASCE)WR.1943-5452.0000626>]{.red}
* [Woodruff, M. J., Reed, P. M., & Simpson, T. W. (2013). Many objective visual analytics: rethinking the design of complex engineered systems. Structural and Multidisciplinary Optimization, 48(1), 201–219. <https://doi.org/10.1007/s00158-013-0891-z>]{.red}
:::

### Techniques/Examples

::: {.wrap-list}
* [Kwakkel - Environmental Modelling & Software, J. H., & 2017. (2017). The Exploratory Modeling Workbench: An open source toolkit for exploratory modeling, scenario discovery, and (multi-objective) robust decision making. Elsevier Oceanography Series, 96, 239–250. <https://doi.org/10.1016/j.envsoft.2017.06.054>]{.red}
* Hadka, D., & Reed, P. (2013). Borg: an auto-adaptive many-objective evolutionary computing framework. Evolutionary Computation, 21(2), 231–259. <https://doi.org/10.1162/EVCO_a_00075>
* Bertoni Federica, Giuliani Matteo, & Castelletti Andrea. (2020). Integrated Design of Dam Size and Operations via Reinforcement Learning. Journal of Water Resources Planning and Management, 146(4), 04020010. <https://doi.org/10.1061/(ASCE)WR.1943-5452.0001182>
* Castelletti, A., Pianosi, F., & Restelli, M. (2013). A multiobjective reinforcement learning approach to water resources systems operation: Pareto frontier approximation in a single run. Water Resources Research, 49(6), 3476–3486. Retrieved from <https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1002/wrcr.20295>
* [Quinn, J. D., Reed, P. M., & Keller, K. (2017). Direct policy search for robust multi-objective management of deeply uncertain socio-ecological tipping points. Environmental Modelling & Software, 92, 125–141. <https://doi.org/10.1016/j.envsoft.2017.02.017>]{.red}
* Rosenstein, M. T., & Barto, A. G. (2001). Robot weightlifting by direct policy search. IJCAI: Proceedings of the Conference / Sponsored by the International Joint Conferences on Artificial Intelligence. Retrieved from <http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.10.5890&rep=rep1&type=pdf>
* Zaniolo, M., Giuliani, M., & Castelletti, A. (2021). Policy Representation Learning for multiobjective reservoir policy design with different objective dynamics. Water Resources Research. <https://doi.org/10.1029/2020wr029329>
* [Zarekarizi, M., Srikrishnan, V., & Keller, K. (2020). Neglecting Uncertainties Biases House-Elevation Decisions to Manage Riverine Flood Risks. Nature Communications. <https://doi.org/10.1038/s41467-020-19188-9>]{.red}
:::


## Other Lists
::: {.callout-tip}
## Good Contribution Opportunity!

What are other categories that would be useful to include in this reading list? Please submit a pull request to add your suggestions!
:::

