---
title: "Onboarding Checklists"
format: 
  html: default
  pdf: default
---

## The Basics
- [ ] Have fun and be safe
- [ ] Review your personal motivation, values, and professional goals

## Coordinate with Adam{#coordinate}

This document is available as a pdf (see the right margin) so that you may download and check/highlight items as you complete them. 

### Before first meeting

- [ ] Review [Lab Values](lab-values/index.qmd)
- [ ] Set up your calendar (e.g., Outlook)
  - Block out working and lunch hours
  - Leave room for lab meetings, journal club, etc.,
  - Set up your weekly meeting schedule with Adam
- [ ] Accept Adam's invitation to our group's lab meeting GitHub repo
- [ ] Make sure you have access to the group's shared-folders directory on OneDrive
- [ ] Find out who to ask for lab meeting invite
- [ ] Find out who to ask for Slack workspace invite
- [ ] Find out who to ask for webpage profile
- [ ] Find out who to talk to at SEES or CLAS for your ID card, office access, etc., if you don't already know
- [ ] Get situated in your office space
  - Get equipment
- [ ] Introduce yourself to the staff that help make our group successful
  - [Angie Bellew](mailto:angela-bellew@uiowa.edu)
  - [Katie Bottorff](mailto:katlin-bottorff@uiowa.edu)
  - [Ali Geraets](mailto:alexandra-geraets@uiowa.edu)
  - [Matthew Wortel](mailto:matthew-wortel@uiowa.edu)
- [ ] Discuss research interests and potential projects

### After first meeting
- [ ] Send photo, bio, contact, socials to web manager
  - [ ] Check out existing profiles (TO DO) for examples
- [ ] Join group Slack and browse/join channels
- [ ] Apply for an [Argon](https://research.its.uiowa.edu/our-services/computing-services/argon-high-performance-computing-hpc) and [IDAS](https://research.its.uiowa.edu/our-services/computing-services/interactive-data-analytics-service-idas) account.
- [ ] Work through required trainings
  - University of Iowa will have some for you

### Before first lab meeting
- [ ] Check out the lab meeting repo (TO DO) and add yourself to the next presentation block
  - Note: Depending on your experience level, you may find it helpful to consult [some examples](analysis/lab-github.qmd).
- [ ] Prepare a 5 minute max presentation to introduce yourself to the group
  - [ ] Review our [presentation guidelines](sci-comm/presentation-guidelines.qmd)

### Losing your training wheels
Now that you have followed these steps, your tasks in the group will become more organic and unique to your chosen path. There is some reading material we strongly recommend for all lab members (and Adam may assign some), but you can otherwise go through the [reading list](materials/reading-list.qmd) as best suits your early exploration and planning stages. Otherwise, work through the tutorials in the [Guide](guide/index.qmd) and find [projects](materials/reproduce-repos.qmd) to reproduce! 


## Set up work environment{#setup}

If you work from a University of Iowa laptop, it will come equipped with a lot of helpful software and functionality. If not, you may have to contribute to the manual to offer guidance for setting up software, tools, etc., Either way, there are still set up steps you will have to follow, such as:

::: {.column-margin}
::: {.callout-note}
It would be great to have guide entries about selecting between various reference managers, and setting up our coding environments!
:::
:::

- [ ] Set up Zotero account and install desktop app and browser plugin
- [ ] [Set up a GitHub account](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github) if you don't have one already
- [ ] Configure your GitHub with [SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh)
- [ ] Set up your coding environment 
  - You will likely run VSCode and Jupyter Notebooks through IDAS, and run scripts through Argon on compute nodes.   
  - I recommend a local computing setup as well. 
- [ ] Set up online profiles
  - [ ] Researchgate
  - [ ] Google scholar
- [ ] Install software that you need for your work. 

While this is an incomplete list, it will hopefully be enough to get you going for the reading list and the guide <i class="fa-regular fa-face-grin-wide"></i>