on:
  push:
    branches: 
      - main

name: Render and Publish

permissions: 
    contents: write
    pages: write
    id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDFs 
          tinytex: true 

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Commit and push
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
        GIT_CONFIG_NAME: "Github Action"
        GIT_CONFIG_EMAIL: actions@github.com
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}