on:
  push:
    branches: 
      - main

name: Render and Publish

permissions: 
    contents: write
    pages: write
    id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDFs 
          tinytex: true 

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        page: '_site/'
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4